#!/bin/bash
eval "$(/usr/bin/garden-exec)"
#set -x -e
name="numpy-mypy"
version="0.1c7"

loadmodules() {
    garden load desres-python/3.6.1-02c7/bin
}

case $1 in
--name)
        echo $name
        ;;
--version)
        echo $version
        ;;
--install)
        mkdir -p $PREFIX/python
        loadmodules

        python3 setup.py install --prefix=$PREFIX --install-lib=$PREFIX/python \
                --single-version-externally-managed --record /dev/null

        # Create a .../lib-python gardenfile
        python2 - >>$GARDENDIR/lib-python <<EOF
print 'prepend-path PYTHONPATH $PREFIX/python'
EOF

                # Create ModulesHelp
        cat >> $PREFIX/ModulesHelp <<EOF
Release notes:

0.1 - Initial release. Still very beta

$name - Numpy plugin for mypy
Version $version
EOF
        #garden with -c -m $GARDENDIR/lib-python py.test tests/ -s .
        ;;
esac
set +e
